apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny.yaml
  - allow-dns.yaml
  - allow-postgres.yaml
  - allow-backend.yaml
  - allow-frontend.yaml
  - allow-backend-egress-postgres.yaml

