apiVersion: v1
kind: ConfigMap

metadata:
  name: taskapp-config
  namespace: taskapp

data:
  DATABASE_HOST: postgres-service

  DATABASE_PORT: "5432"

  DATABASE_NAME: taskapp

  FLASK_ENV: production

  FRONTEND_URL: https://app.alameendevops.click

  API_URL: https://api.alameendevops.click
